//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RellenoBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class alarma
    {
        public alarma()
        {
            this.alumno_has_alarma = new HashSet<alumno_has_alarma>();
        }
    
        public int Id { get; set; }
        public string Asunto { get; set; }
        public Nullable<System.DateTime> Dia_Hora { get; set; }
    
        public virtual ICollection<alumno_has_alarma> alumno_has_alarma { get; set; }
    }
}
