//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RellenoBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumno_has_alarma
    {
        public string Alumno_Rut { get; set; }
        public int Alarma_Id { get; set; }
        public int Id { get; set; }
    
        public virtual alarma alarma { get; set; }
        public virtual alumno alumno { get; set; }
    }
}
