//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RellenoBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumno
    {
        public alumno()
        {
            this.alumno_has_alarma = new HashSet<alumno_has_alarma>();
            this.alumno_has_seccion = new HashSet<alumno_has_seccion>();
            this.asistencia = new HashSet<asistencia>();
            this.nota = new HashSet<nota>();
            this.pago = new HashSet<pago>();
        }
    
        public string Rut { get; set; }
        public string Nombre { get; set; }
        public string Contraseña { get; set; }
        public string Correo { get; set; }
        public int Carrera_Id { get; set; }
    
        public virtual carrera carrera { get; set; }
        public virtual ICollection<alumno_has_alarma> alumno_has_alarma { get; set; }
        public virtual ICollection<alumno_has_seccion> alumno_has_seccion { get; set; }
        public virtual ICollection<asistencia> asistencia { get; set; }
        public virtual ICollection<nota> nota { get; set; }
        public virtual ICollection<pago> pago { get; set; }
    }
}
