//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RellenoBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class dia
    {
        public dia()
        {
            this.horario = new HashSet<horario>();
        }
    
        public int Id { get; set; }
        public string Dia_Semana { get; set; }
    
        public virtual ICollection<horario> horario { get; set; }
    }
}
