//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RellenoBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class horario_seccion
    {
        public int Id { get; set; }
        public int Horario_Id { get; set; }
        public int Seccion_Id { get; set; }
        public int Sala_Id { get; set; }
    
        public virtual horario horario { get; set; }
        public virtual sala sala { get; set; }
        public virtual seccion seccion { get; set; }
    }
}
