//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RellenoBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class horario
    {
        public horario()
        {
            this.horario_seccion = new HashSet<horario_seccion>();
        }
    
        public int Id { get; set; }
        public Nullable<System.TimeSpan> HoraInicio { get; set; }
        public Nullable<System.TimeSpan> HoraFin { get; set; }
        public int Dia_Id { get; set; }
    
        public virtual dia dia { get; set; }
        public virtual ICollection<horario_seccion> horario_seccion { get; set; }
    }
}
