//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RellenoBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota
    {
        public int Id { get; set; }
        public Nullable<decimal> Nota1 { get; set; }
        public Nullable<int> Ponderacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Alumno_Rut { get; set; }
        public int Seccion_Id { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual seccion seccion { get; set; }
    }
}
