//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RellenoBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago
    {
        public int Id { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaVenc { get; set; }
        public string Concepto { get; set; }
        public Nullable<int> Monto { get; set; }
        public string Alumno_Rut { get; set; }
    
        public virtual alumno alumno { get; set; }
    }
}
