//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RellenoBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class sala
    {
        public sala()
        {
            this.horario_seccion = new HashSet<horario_seccion>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Piso { get; set; }
    
        public virtual ICollection<horario_seccion> horario_seccion { get; set; }
        public virtual horarios_has_sala horarios_has_sala { get; set; }
    }
}
